#FIX INDENTATION
StoreName = input("What is the name of your store? ")
StoreAddress = input("What is the address of your store? ")
StoreShortName = input("What is the short name of your store? ")
StoreCity = input("What city is your store in? ")
StoreNumber = input("What is the phone number of your store? ")
StoreWebsite = input("What is the website of your store? ")
item1 = input("What is your first item? ")
item1_ogprice = float(input("How much did it cost? "))
item1_quantity = int(input("How many did you buy? "))
item1_finalprice = float(item1_ogprice)*float(item1_quantity)
item2 = input("What is your second item? ")
item2_ogprice = float(input("How much did it cost? "))
item2_quantity = int(input("How many did you buy? "))
item2_finalprice = float(item2_ogprice)*float(item2_quantity)
taxes = int(input("How much was tax? "))
tips = int(input("How did you tip? "))
print(f"{StoreName:^38}")
print(f"{StoreAddress:^38} \n {StoreCity:^38} \n {StoreShortName:^38}")
print(f"{StoreNumber:^38}")
print(f"{StoreWebsite:^38}")
print("-"*40)
print("Item\t Quantity\tPrice\tTotal")
print("-"*40)
print(f"{item1:^}\t{item1_quantity}@\t${item1_ogprice:>.2f}\t${item1_finalprice:>
.2f}")
print(f"{item2:^}
\t{item2_quantity}@\t${item2_ogprice:>.2f}\t${item2_finalprice:>.2f}")
print("-"*40)
print(f"Subtotal:\t\t\t${item1_finalprice + item2_finalprice:>.2f}")
print(f"Tax:\t\t\t\t${taxes:>.2f}")
print(f"Tip:\t\t\t\t${tips:>.2f}")
print("-"*40)
print(f"Total:\t\t\t\t${item1_finalprice + item2_finalprice + taxes +
tips:>.2f}")
print("-"*40)
print(f"Thank you for shopping at {StoreShortName}!"
